In [24]:
import numpy as np

array_1D = np.random.rand(1,5)
print(array_1D)
print("Datatype: Array ",type(array_1D))
print("Shape: ",array_1D.shape)
print("Dimension: ",array_1D.shape[0])

[[0.80696839 0.1037321  0.3587472  0.10611753 0.95328283]]
Datatype: Array  <class 'numpy.ndarray'>
Shape:  (1, 5)
Dimension:  1


In [25]:
array_2D = np.random.rand(5,5)
print(array_2D)
print("Datatype: Array ",type(array_2D))
print("Shape: ",array_2D.shape)
print("Dimension: ",array_2D.shape[0])

[[0.10353818 0.63825416 0.50546669 0.04172726 0.29891276]
 [0.17978092 0.92385876 0.4570759  0.87804883 0.69677083]
 [0.29107512 0.88366782 0.89152688 0.02590982 0.48377727]
 [0.7677209  0.39603873 0.65728922 0.37061156 0.27732382]
 [0.69081669 0.33072643 0.64602693 0.92125034 0.19143357]]
Datatype: Array  <class 'numpy.ndarray'>
Shape:  (5, 5)
Dimension:  5
