In [1]:
import numpy as np

In [2]:
#1 Random Initialization
array_1D = np.random.rand(1,5)
array_2D = np.random.rand(3,5)
print(array_1D)
print(array_2D)

[[0.02669237 0.66146922 0.53538616 0.32498177 0.02638163]]
[[0.00338381 0.60734579 0.11025465 0.5107912  0.67998483]
 [0.698802   0.9459226  0.57948641 0.26180745 0.43348208]
 [0.60965229 0.87660687 0.08349266 0.83790868 0.01717283]]


In [3]:
#2 Default Initialization

array_1D = np.array([1,2,4])
array_2D = np.array([[1,2,4],[2,4,6],[5,6,3]])
print(array_1D)
print(array_2D)

[1 2 4]
[[1 2 4]
 [2 4 6]
 [5 6 3]]


In [4]:
#3 Diagonal Values

print("Diagonal Elements:", end=" ")
for i in range(0,len(array_2D)):
    for j in range(0,len(array_2D[0])):
        if i==j:
            print(array_2D[i][j], end=" ")

Diagonal Elements: 1 4 3 

In [5]:
#4 First Element
print("First Element")
print("1D: ", array_1D[0])
print("2D: ", array_2D[0][0])
#5 Last Element
print("Last Element")
print("1D: ", array_1D[-1])
print("2D: ", array_2D[-1][-1])

First Element
1D:  1
2D:  1
Last Element
1D:  4
2D:  3


In [6]:
#6 2nd row and 2nd column Element
print(array_2D[2][2])

3


In [7]:
#7 Number of elements
print(len(array_1D))
print(array_2D.shape)

3
(3, 3)


In [9]:
#Q4 Range of values 
print("Range of 1D array: ",array_1D.max()-array_1D.min())
print("Range of 2D array: ",array_2D.max()-array_2D.min())

Range of 1D array:  3
Range of 2D array:  5


In [14]:
#Q5 Reshape an array
arr = np.array([1,2,3,4,5,6,7,8,9,10])
newArr = arr.reshape(5,2)
print("After reshaping 1D to 2D array: \n",newArr)

After reshaping 1D to 2D array: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
