In [13]:
import numpy as np

In [14]:
arr1 = np.random.randint(low=1,high=50,size=9)
arr1 = arr1.reshape(3,3)
arr2 = np.random.randint(low=1,high=50,size=9)
arr2 = arr2.reshape(3,3)


In [15]:
print("Arr1: \n",arr1)
print("Determinant: ",np.linalg.det(arr1))
print("\nArr2: \n",arr2)
print("Determinant: ",np.linalg.det(arr2))

Arr1: 
 [[25  4 24]
 [15 15 17]
 [12 35 17]]
Determinant:  -424.0

Arr2: 
 [[28  4 19]
 [34  5 46]
 [ 3  2 10]]
Determinant:  -977.0000000000005


In [27]:
print("Addition: \n",arr1+arr2)
print("Multiplication or Dot Product: \n",np.dot(arr1,arr2))
print("Subtraction: \n",arr1-arr2)
print("Division: \n",arr1/arr2)

Addition: 
 [[53  8 43]
 [49 20 63]
 [15 37 27]]
Multiplication or Dot Product: 
 [[ 908  168  899]
 [ 981  169 1145]
 [1577  257 2008]]
Subtraction: 
 [[ -3   0   5]
 [-19  10 -29]
 [  9  33   7]]
Division: 
 [[ 0.89285714  1.          1.26315789]
 [ 0.44117647  3.          0.36956522]
 [ 4.         17.5         1.7       ]]


In [28]:
print("Transpose: ")
print("Arr1:\n",np.transpose(arr1))
print("Arr2:\n",np.transpose(arr2))

Transpose: 
Arr1:
 [[25 15 12]
 [ 4 15 35]
 [24 17 17]]
Arr2:
 [[28 34  3]
 [ 4  5  2]
 [19 46 10]]


In [30]:
print("Cross Product: \n", np.cross(arr1,arr2))
print("dot Product: \n", np.dot(arr1,arr2))

Cross Product: 
 [[ -20  197  -12]
 [ 605 -112 -435]
 [ 316  -69  -81]]
dot Product: 
 [[ 908  168  899]
 [ 981  169 1145]
 [1577  257 2008]]
